[package]
name = "sorock-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
crossbeam = "0.8.4"
http = "1.1.0"
rand = "0.8.5"
ratatui = "0.28.1"
tokio = { version = "1.40.0", features = ["full"] }
tui-widget-list = "0.12.2"
